java Project 5 pgm/baboon.ascii.pgm rln/baboon.rn
java Project 5 pgm/balloons.ascii.pgm rln/balloons.rn
java Project 5 pgm/barbara.ascii.pgm rln/barbara.rn
java Project 5 pgm/brain_398.ascii.pgm rln/brain_398.rn
java Project 5 pgm/casablanca.ascii.pgm rln/casablanca.rn
java Project 5 pgm/coins.ascii.pgm rln/coins.rn
java Project 5 pgm/columns.ascii.pgm rln/columns.rn
java Project 5 pgm/dragon.ascii.pgm rln/dragon.rn
java Project 5 pgm/gator.ascii.pgm rln/gator.rn
java Project 5 pgm/mona_lisa.ascii.pgm rln/mona_lisa.rn
java Project 6 rln/baboon.rn rln/baboon.pgm
java Project 6 rln/balloons.rn rln/balloons.pgm
java Project 6 rln/barbara.rn rln/barbara.pgm
java Project 6 rln/brain_398.rn rln/brain_398.pgm
java Project 6 rln/casablanca.rn rln/casablanca.pgm
java Project 6 rln/coins.rn rln/coins.pgm
java Project 6 rln/columns.rn rln/columns.pgm
java Project 6 rln/dragon.rn rln/dragon.pgm
java Project 6 rln/gator.rn rln/gator.pgm
java Project 6 rln/mona_lisa.rn rln/mona_lisa.pgm